import { Locale, i18n } from '@/i18n.config';
import AppWrapper from '@/shared/AppWrapper';
import Navbar from '@/shared/Navbar';
import ThemeSwitch from '@/shared/ThemeSwitch';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: Locale };
}) {
	const getHtmlDirection = (lang: Locale) => {
		switch (lang) {
			case 'he':
				return 'rtl';
			case 'en':
				return 'ltr';
			default:
				return 'ltr';
		}
	};
	return (
		<html lang={params.lang} dir={getHtmlDirection(params.lang)}>
			<body className={inter.className}>
				<AppWrapper>
					<ThemeSwitch />
					<h1 className='text-3xl font-bold underline'>Hello, Next.js!</h1>
					<Navbar params={params} />
					{children}
				</AppWrapper>
			</body>
		</html>
	);
}
